### ISSUE TITLE
Deno requests network access to "deno.land"

### ISSUE THREAD

**Issue by scarf005** [linus/doctest#5]
```ts
// add.ts
/**
 * @example add(1, 2)
 * //=> 3
 */
export const add = (a: number, b: number) => a + b
```
```ts
// doc_test.ts
import { doctest } from "https://deno.land/x/doctest@0.3.0/mod.js"

Deno.test("doctest", doctest("./add.ts"))
```
```sh
$ deno test --allow-read
running 1 test from ./doc_test.ts
doctest ...┌ ⚠️  Deno requests network access to "deno.land".
├ Requested by `Deno.permissions.query()` API.
├ Run again with --allow-net to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all net permissions) > 
```
I'm not sure what does this means.

**Comment by tiagoefmoraes** [comment]
Looks like it's how [deno_doc](https://deno.land/x/deno_doc) works, it downloads `https://deno.land/x/deno_doc@0.62.0/deno_doc_bg.wasm`.

https://github.com/denoland/deno_doc/issues/335#issuecomment-1583261442 comments on this behaviour.

It still asks for permission every time the tests run, even when updating to `0.62.0`.

```
error: TypeError: error sending request for url (https://deno.land/x/deno_doc@0.62.0/deno_doc_bg.wasm): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
      const wasmResponse = await fetch(wasmUrl);
                           ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async instantiateModule (https://deno.land/x/deno_doc@0.62.0/deno_doc.generated.js:718:28)
    at async https://deno.land/x/deno_doc@0.62.0/deno_doc.generated.js:659:27
    at async instantiate (https://deno.land/x/deno_doc@0.62.0/deno_doc.generated.js:637:11)
    at async doc (https://deno.land/x/deno_doc@0.62.0/mod.ts:80:16)
    at async doctest (https://deno.land/x/doctest@0.3.0/mod.js:16:17)
```
